# Generated by Django 5.2 on 2025-04-18 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(auto_now_add=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(choices=[('eng', 'English'), ('Math', 'Mathematics'), ('sci', 'Science'), ('social', 'Social_std')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said_by', models.CharField(choices=[('ai', 'AI'), ('student', 'Student')], max_length=10)),
                ('said_at', models.DateTimeField(auto_now_add=True)),
                ('type_of', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='AI_tutor.convo')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='convo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_tutor.student'),
        ),
    ]
